version: '3.4'
services:
  postgres:
    container_name: postgres10
    image: postgres:10.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata           
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata

volumes:
  postgres: