version: '3.4'
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: test123
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - '6379:6379'
volumes:
  redis: